### ISSUE TITLE
Не могу создать миграцию после добавления нового поля

### ISSUE THREAD

**Issue by Dmitriy-Bychkov** [Dmitriy-Bychkov/Course_project_6.mailer#3]
Добавили поле last_sended в модель Mailing и изменили логику функции get_objects_for_send.
Появляется такая ошибка:

(course-project-6-mailer-py3.11) dmitriy@dmitriy-VirtualBox:~/PycharmProjects/Course_project_6.mailer$ python3 manage.py makemigrations
Traceback (most recent call last):
  File "/home/dmitriy/PycharmProjects/Course_project_6.mailer/manage.py", line 22, in <module>
    main()
  File "/home/dmitriy/PycharmProjects/Course_project_6.mailer/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/dmitriy/.cache/pypoetry/virtualenvs/course-project-6-mailer-CMMUUIYh-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/dmitriy/.cache/pypoetry/virtualenvs/course-project-6-mailer-CMMUUIYh-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/home/dmitriy/.cache/pypoetry/virtualenvs/course-project-6-mailer-CMMUUIYh-py3.11/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/dmitriy/.cache/pypoetry/virtualenvs/course-project-6-mailer-CMMUUIYh-py3.11/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/home/dmitriy/.cache/pypoetry/virtualenvs/course-project-6-mailer-CMMUUIYh-py3.11/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dmitriy/PycharmProjects/Course_project_6.mailer/mail/models.py", line 4, in <module>
    from mail.services import send_mail_task
  File "/home/dmitriy/PycharmProjects/Course_project_6.mailer/mail/services.py", line 4, in <module>
    from mail.models import Mailing
ImportError: cannot import name 'Mailing' from partially initialized module 'mail.models' (most likely due to a circular import) (/home/dmitriy/PycharmProjects/Course_project_6.mailer/mail/models.py)

**Comment by Dmitriy-Bychkov** [comment]
Миграцию создал. Закомментил временно файл services.py, добавил в поле last_sent значение **NULLABLE и миграция прошла успешно, поле добавилось в БД.

Теперь нужно разбираться дальше с функцией get_objects_for_send чтобы она выбирала рассылки по условиям, ежедневно\еженедельно\ежемесячно

**Comment by alfa24** [comment]
@Dmitriy-Bychkov это мы поймали рекурсивный импорт. Когда из файлика models импортируется services. А из файла services импортируется models.

попробуй вот эту строчку https://github.com/Dmitriy-Bychkov/Course_project_6.mailer/blob/9f113b4e19707312b9d7e8a04191c0d4150274e5/mail/services.py#L4 переместить на 26 строку


Или более правильным будет, метод https://github.com/Dmitriy-Bychkov/Course_project_6.mailer/blob/9f113b4e19707312b9d7e8a04191c0d4150274e5/mail/services.py#L7 перенести в отдельный файл (создать новый) clents.py или email.py чтобы из models убрать импорт services.send_email_task
