### ISSUE TITLE
Отправка рассылки по распианию

### ISSUE THREAD

**Issue by Dmitriy-Bychkov** [Dmitriy-Bychkov/Course_project_6.mailer#5]
@alfa24
Сейчас создал новую рассылку со статусом created и периодом daily. Время старта: 19 сентября 2023 г. 0:00, время окончания: 19 сентября 2023 г. 23:59.
Отправка по кнопке происходит незамедлительно с созданием лога,  как и должно быть.
Теперь пытаюсь запускать не через крон, а вручную с помощью команды  python manage.py start_send_mail и возникает следующая ошибка:

Traceback (most recent call last):
  File "/home/dmitriy/PycharmProjects/Course_project_6.mailer/manage.py", line 22, in <module>
    main()
  File "/home/dmitriy/PycharmProjects/Course_project_6.mailer/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/dmitriy/.cache/pypoetry/virtualenvs/course-project-6-mailer-CMMUUIYh-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/dmitriy/.cache/pypoetry/virtualenvs/course-project-6-mailer-CMMUUIYh-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dmitriy/.cache/pypoetry/virtualenvs/course-project-6-mailer-CMMUUIYh-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/dmitriy/.cache/pypoetry/virtualenvs/course-project-6-mailer-CMMUUIYh-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmitriy/PycharmProjects/Course_project_6.mailer/users/management/commands/start_send_mail.py", line 9, in handle
    send_mailing_task()
  File "/home/dmitriy/PycharmProjects/Course_project_6.mailer/mail/services.py", line 8, in send_mailing_task
    mailing_list = Mailing.get_objects_for_send()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmitriy/PycharmProjects/Course_project_6.mailer/mail/models.py", line 120, in get_objects_for_send
    m.last_sent.year == now.year,
    ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'year'

**Comment by alfa24** [comment]
@Dmitriy-Bychkov А он ругается что в last_sent нет данных, а мы пытаемся получить год.

для проверки сначала давай у всех записей установим какой нибудь last_sent

а потом уже добавим дополнительные проверки, проверяющие, что он заполнен.
